### ISSUE TITLE
Java Error when trying to convert waypoints. 

### ISSUE THREAD

**Issue by kmbrady42** [rfresh2/JMWaypointsToXaero#1]
Trying to convert JourneyMap waypoints to Xaero's and getting the below error over and over. Tried it with Java 8 and 17, same issue. 

Error Message:
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "colorizedIcon" (class com.github.rfresh2.JourneyMapWaypointsToXaero$JourneyMapWaypoint), not marked as ignorable (14 known properties: "b", "enable", "origin", "g", "name", "dimensions", "r", "persistent", "x", "icon", "z", "id", "y", "type"])
 at [Source: (File); line: 5, column: 21] (through reference chain: com.github.rfresh2.JourneyMapWaypointsToXaero$JourneyMapWaypoint["colorizedIcon"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2023)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1678)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:319)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3494)
	at com.github.rfresh2.JourneyMapWaypointsToXaero.parseJourneyMapWaypointFile(JourneyMapWaypointsToXaero.java:80)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at com.github.rfresh2.JourneyMapWaypointsToXaero.convertWaypoints(JourneyMapWaypointsToXaero.java:41)
	at com.github.rfresh2.JourneyMapWaypointsToXaero.main(JourneyMapWaypointsToXaero.java:32)

**Comment by KingColton1** [comment]
Hi! I know it have been a while but I did not have the need for switching from JourneyMap to Xaeros until few days ago where I need to move from JM to Xaeros and found out this is a broken jar. Since this author seem to be not maintaining this repo so I decided to fork and fix it for you guys who are having issues with this.

https://github.com/KingColton1/JMWaypointsToXaero/releases/tag/1.1

I hope this help you and others who are looking for this.

**Comment by rfresh2** [comment]
@KingColton1 i'm happy to take a PR

honestly did not see this issue before, must've slipped through my notifications. And i haven't actively kept up to date with any journeymap changes

**Comment by KingColton1** [comment]
@rfresh2 oh I see, no worries I made PR for you

**Comment by rfresh2** [comment]
release with fix is now published https://github.com/rfresh2/JMWaypointsToXaero/releases/tag/1.1
